ver 0.1
alexunder123/GophKeeper pull request #1
Opened 2023-04-27 17:07 UTC by alexunder123

2023-05-11 18:31 UTC, kilchik requested changes
По структуре: такая плоская структура internal плохо читается: тут на одном уровне и handler (относится к серверу) и menu (относится к клиенту). Кажется, что проект выиграет от более иерархической структуры. Можно выделить директории /internal/server и /internal/client для лучшей гранулярности.
Здорово выглядит gracefule shutdown.
Я бы пересмотрел хранение секретов на сервере в сторону использования БД

2023-05-11 18:31 UTC, kilchik commented on internal/handler/server.go
> +		log.Error().Err(err).Msg("UserData getData error")
Старайся по всему коду снабжать логи всеми деталями, которые могут пригодиться при расследовании ошибок (за исключением конфиденциальных данных разумеется). zerolog - структурированный логер, в него можно добавлять доп поля, по которым потом можно строить индексы. Например, узнав userID, его тут же можно добавить в логируемые параметры
```
log := logger.With().Str("user_id", UserID)
log.Error().Err(err).Msg("UserData getData error")
```

2023-05-11 18:31 UTC, kilchik commented on internal/storage/storage.go
> +func createDB(db *sql.DB) error {
Лучше разделять сервер и процесс, накатывающий на базу миграции. Представь, что тебе понадобится накатить новую миграцию на уже существующую базу с живыми пользователями: если ты это будешь делать из кода, ты не сможешь контролировать версию изменений, твой код должен будет каждый раз определять актуальную версию изменений и применять только те миграции, которые еще не применены. Посмотри вот на этот инструмент https://github.com/pressly/goose. Он очень популярен в сообществе и решает описанную проблему

2023-05-11 18:31 UTC, kilchik commented on internal/storage/storage.go
> +	s.RLock()
В чем достоинство хранения секретов в файлах? Почему не хранить в БД?
Получилась очень сложная логика работы с локами, которой не понадобится, если записывать данные в БД. Кроме того такие локи перестанут работать, если запустить не одну реплику твоего сервера, а несколько. Помимо этого существует еще ряд проблем, которые предстоит тебе решать самостоятельно, если не положишься на БД:
- нужно реализовывать эффективный поиск по файлу самостоятельно
- при высокой нагрузке серверу придется одновременно работать с очень многими файлами, что приведет к огромному количеству используемой памяти
- нужно самостоятельно решать проблему транзакционности (пользователь начал заливать секрет, сеть моргнула, секрет залился наполовину)
- многие другие

2023-05-11 18:31 UTC, kilchik commented on internal/grpc/proto/grpc.proto
> +syntax = "proto3";
proto-файл - по сути API приложения, я бы его не хранил в internal. Можно расположить в /api, можно перенести в корень

2023-05-11 18:31 UTC, kilchik commented on internal/crypto/crypto.go
> +			time.Sleep(time.Hour * time.Duration(period) / 2)
Лучше воспользоваться time.Ticker

2023-05-16 16:24 UTC, alexunder123 commented on internal/handler/server.go
> +		log.Error().Err(err).Msg("UserData getData error")
Учту на будущее

2023-05-16 16:24 UTC, alexunder123 commented on internal/storage/storage.go
> +func createDB(db *sql.DB) error {
Добавил миграции

2023-05-16 16:25 UTC, alexunder123 commented on internal/storage/storage.go
> +	s.RLock()
Заменил на хранение в БД

2023-05-16 16:25 UTC, alexunder123 commented on internal/grpc/proto/grpc.proto
> +syntax = "proto3";
Перенес

2023-05-16 16:25 UTC, alexunder123 commented on internal/crypto/crypto.go
> +			time.Sleep(time.Hour * time.Duration(period) / 2)
Изменил

2023-05-23 17:29 UTC, kilchik requested changes
Структура выглядит здорово.
Работа с ошибками выглядит здорово.
Смотри, у тебя реляционная база, а секреты в ней хранятся как набор байтов, хотя можно было бы сделать в отдельной таблице. Так можно будет понавесить индексы на ключи и искать нужный пользователю секрет без необходимости скачивать весь блоб целиком (этот момент - на будущее)
Тесты скомпилировать не удалось.
Очень нужны инструкции по запуску и тестированию - не смог ни запустить, ни протестировать

2023-05-23 17:29 UTC, kilchik commented on internal/server/handler/server.go
> +		log.Error().Err(err).Msg("NewSessionID writing to buf error")
Смотри, без доп атрибутов логи не принесут ценности. У тебя в логах будет запись вида "NewSessionID writing to buf error: some error". К тебе приходит заказчик и говорит, что пользователь такой-то жалуется, что у него не работает клиент, сервер запущен, как понять, почему у него возникла проблема? К БД у тебя доступа нет, к клиенту - тем более.

2023-05-23 17:29 UTC, kilchik commented on internal/server/handler/server.go
> +	dec := gob.NewDecoder(&buf)
А зачем ты дополнительно кодируешь gob'ом?

2023-05-23 17:29 UTC, kilchik commented on cmd/client/main.go
> +	conn, err := grpc.Dial(cnfg.RunAddress, grpc.WithTransportCredentials(insecure.NewCredentials()))
Давай все-таки использовать SSL

2023-05-23 17:29 UTC, kilchik commented on internal/server/handler/server.go
> +	userID, err := s.rsa.CheckSign(in.SessionID, in.UserSign)
CheckSign лучше вынести в интерсептор

2023-05-23 17:29 UTC, kilchik commented on internal/client/storage/user_storage.go
> +func (s *UserStorage) AddUserData(i int) {
int - ничего не говорит читающему код, должна быть типизированная константа с говорящим названием

2023-05-23 17:29 UTC, kilchik commented on internal/client/storage/user_storage.go
> +func (s *UserStorage) StringUserData(i, v int) {
В UserStorage все смешалось: тут и парсинг входных данных, и приглашение пользователю ввести команду, и хранение данных. Все это - три разных задачи, для каждой нужен отдельный компонент. Можно оставить взаимодействие с пользователем в одном пакете, но хранение и отправка - точно другой компонент, который отвечает только за отправку и получение

2023-05-23 17:29 UTC, kilchik commented on cmd/client/main.go
> +	logger.Newlogger()
Если делать логер в Stdout, то пользователю будут видны и логи и сообщения одним потоком. Нужно логи выводить в отдельный файл, чтобы они не путались с командами и сообщениями от клиента

2023-05-23 17:29 UTC, kilchik commented on README.md
> +Основные тезисы работы программы:
Нужен Makefile, либо добавить сюда, как запустить клиент и сервер с примерами конфигов

2023-05-23 17:29 UTC, kilchik commented on internal/client/sender/client.go
> +func (c *GophKeeperClient) LockUserData() error {
Я запутался, а где происходит Unlock? Кажется, пользователь никогда повторно не сможет установить сессию. Если ты хочешь ограничить число сессий для пользователя, то это стоит делать по-другому: нужно сделать таблицу (user_id, timestamp) и навесить ограничение на уникальность user_id. Чтобы лок не висел вечность, потребуется в фоне удалять локи старше какого-то времени

2023-06-12 09:42 UTC, alexunder123 commented on internal/server/handler/server.go
> +		log.Error().Err(err).Msg("NewSessionID writing to buf error")
Дополнил строки атрибутами по возможности

2023-06-12 09:44 UTC, alexunder123 commented on internal/server/handler/server.go
> +	dec := gob.NewDecoder(&buf)
я свернул сложную структуру в слайс, или ключ нужно обязательно передавать структурой как есть?

2023-06-13 13:45 UTC, alexunder123 commented on cmd/client/main.go
> +	logger.Newlogger()
Добавил ведение лог-файла

2023-06-13 13:47 UTC, alexunder123 commented on internal/client/sender/client.go
> +func (c *GophKeeperClient) LockUserData() error {
Unlock происходит на сервере автоматически после внесения изменений пользователем. Либо он сбрасывается при запросе на блокировку или сохранение данных при истекшем сроке действия блокировки.

2023-06-14 12:55 UTC, alexunder123 commented on cmd/client/main.go
> +	conn, err := grpc.Dial(cnfg.RunAddress, grpc.WithTransportCredentials(insecure.NewCredentials()))
Добавил

2023-06-15 13:30 UTC, alexunder123 commented on internal/client/storage/user_storage.go
> +func (s *UserStorage) AddUserData(i int) {
Изменил

2023-06-15 13:31 UTC, alexunder123 commented on internal/client/storage/user_storage.go
> +func (s *UserStorage) StringUserData(i, v int) {
Выделил из хранилища работу с пользователем, оставил только относящееся к хранению данных

2023-06-15 17:04 UTC, alexunder123 commented on internal/server/handler/server.go
> +	userID, err := s.rsa.CheckSign(in.SessionID, in.UserSign)
вынес

2023-06-21 10:02 UTC, lugingf approved these changes
Работу и замечания предыдущего ревьюера обсуждали голосом. Работу принимаю, в общем все очень хорошо. Большое спасибо!

P.S. все еще не получается принять ДЗ на практикуме, попроси плз кураторов это сделать с их стороны

2023-06-21 12:30 UTC, merged